### ISSUE TITLE
Execution engine API communication

### ISSUE THREAD

**Issue by raprasad** [opendp/dpcreator#36]
(placeholder issue)

## (1) Validation endpoint

**Inputs**

1. Analysis object (computational graph) 
2. DP metadata

**Outputs** (current)

1. Validation of privacy 
2. Will it be able to enforce epsilon/delta levels? (How much will each statistic "cost"?)

**To do**

- Input format
- Output format

## (2) Execution endpoint

**Inputs** 
1. Analysis object (computational graph) 
2. DP metadata
3. DV token
4. DV file url

**Outputs**
1. Pointer
    - [ ] need to define
    
## (3) Status Updates 

- DP Tool checks status
- [ ] format of status check 
- [ ] output of status check

## (4) Release (Upon Successful Execution)

- [ ] Retrieve DP Result, create derivatives, etc. #31, #32, #33, #34

## (5) Upon Failed Execution

- [ ] once complete, send error back to Dataverse user

**Comment by mikephelan** [comment]
app for exec engine API endpoints:
exec_eng
branch:
36_exec_eng_api_comms

**Comment by raprasad** [comment]
no longer using this model
