### ISSUE TITLE
Execution engine testing w/o DV

### ISSUE THREAD

**Issue by raprasad** [opendp/dpcreator#38]
How can we test DP Tool / Execution Engine functionality using a test file uploaded to the DP Tool (instead of a Dataverse file)?  

---
Related to #36

**Comment by raprasad** [comment]
One method is to use the existing dataverse adapter and **change the host**.

e.g.: https://github.com/opendifferentialprivacy/whitenoise-system/blob/f2058b69a5acdb04593a0ea5e1a119747d4f6149/sdk/opendp/whitenoise/data/dataverse_adapter.py

e.g. the DP tool can mock this url to download a file. (For the `doi`, use a UUID linked to an uploaded file on the DP Tool)

```python
def _make_doi_host(host, doi):
    doi = doi.replace("doi:", "")
    return "{}/api/access/datafile/:persistentId/?persistentId=doi:{}".format(host, doi)
```

**Comment by mikephelan** [comment]
First step: creating mock endpoints in the OpenDP API, to be backed by calls to an ML lifecycle platform, such as MLFlow

**Comment by mikephelan** [comment]
Mock endpoints completed

**Comment by raprasad** [comment]
no longer using ML Flow
